### ISSUE TITLE
since enigma update this week, imported  m3u channels appear as <n/a> 

### ISSUE THREAD

**Issue by FrankInsink** [DYefremov/DemonEditor#112]
Since enigma update this week, imported m3u channels using demoneditor appear as <n/a>. 
They cannot be deleted on Enigma.
Manually added channels in enigma work ok. 
I have updated my Demon Editor to 2.2.4.

**Comment by DYefremov** [comment]
Hi,
Аre you sure the problem is with the editor, not with the enigma2 image you are using?

Also, it's not entirely clear:
1. What image are you using.
2. What OS are you using.
3. Which playlist are you importing.
4. With what options do you import the playlist. (type of service, etc.).

With openATV 7.0 from 17.08.2022, I personally do not observe any problems.
