### ISSUE TITLE
iptv stream 

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#164]
demon v 3.5.0 have bugs

1-Downloading bouquets from stb not closed at the end

![image](https://user-images.githubusercontent.com/65136999/223571756-bbe9e729-5337-4a5c-8600-bbe684558028.png)

2 working stream detected as not working ( not playing) and when checking-removing

`http://84.244.187.150:1935/live/smil:myStream.smil/chunklist.m3u8
`

![image](https://user-images.githubusercontent.com/65136999/223572085-7bceb89e-5e0c-4ea1-9859-dd766688ee25.png)

**Comment by DYefremov** [comment]
> demon v 3.5.0 have bugs

There no changes in work with data download and streams from previous version! 

> 1-Downloading bouquets from stb not closed at the end

Have you already checked the download on the previous program version? I can't reproduce it. Perhaps you have changed your bouquets in third-party plugins or manually.

> working stream detected as not working ( not playing) and when checking-removing

Can't confirm deletion. At me it's OK. In terms of playback. This problem exists, but only on **Windows**. Perhaps the problem is in one of the libraries. For example,  don't 'likes' link format (or some symbol).

**Comment by luxorko** [comment]
regarding downloding:

v 3.4.2 - no problem

![image](https://user-images.githubusercontent.com/65136999/223661179-21a368dc-e22d-4469-8760-951b8196f491.png)

v3.5.0 - have problem

![image](https://user-images.githubusercontent.com/65136999/223661413-61689e1b-8ba0-45d3-a9ae-67fb1b66c97d.png)

**Comment by luxorko** [comment]
`Can't confirm deletion. At me it's OK. In terms of playback. This problem exists, but only on Windows. Perhaps the problem is in one of the libraries. For example, don't 'likes' link format (or some symbol).`

These URL (stream) are playing on VLC and PotPlayer without any problem.., 

why demon cannot opeing stream on Pot player

![image](https://user-images.githubusercontent.com/65136999/223663187-39b3cddd-5c12-46cf-b81c-523f3510ed9b.png)

or VLC

![image](https://user-images.githubusercontent.com/65136999/223663505-130c05e9-dbf0-41e7-b363-f39e5b624d5b.png)

**Comment by luxorko** [comment]
..and what wrong with these stream?  also not works on demon

`https://tv-trtkurdi.medya.trt.com.tr/master.m3u8`

bouquet looks 

`#SERVICE 4097:0:1:1:0:0:0:0:0:0:https%3a//tv-trtkurdi.medya.trt.com.tr/master.m3u8
#DESCRIPTION TRT Kurdi`

**Comment by luxorko** [comment]
looks like demon have problem playing streams with end ".m3u8"

**Comment by DYefremov** [comment]
> v3.5.0 - have problem

It's strange...  I checked with all my presets. In the latest version, I added an additional optimization that does not allow you to load duplicates to the main list.  Perhaps this is related. It is advisable to get your full set of settings to check. Just zip your settings folder (all bouquets and lamedb) and send me on email for my profile. 


> and what wrong with these stream? anot working

This is on Windows:
![stream](https://user-images.githubusercontent.com/7511379/223688140-97fa25ce-4ea9-4c7e-86f8-0d4d87b6f4b1.png)

> why demon cannot opeing stream on Pot player

Since this player has nothing to do with this program. The Windows build uses [MPV](https://mpv.io/) by default. The library is already included in the package.  You can optionally use VLC. But correct operation on WIndows is not guaranteed. VLC should be installed by default (int to Program Files).

> These URL (stream) are playing on VLC

The problem may be in other libraries as well. Also, blocking stream playback on the server side cannot be ruled out (GEO blocking etc). This issue is secondary. The main thing is that with the **data loading**. I repeat. All my presets load without problems.

**Comment by luxorko** [comment]
found it

problem are in bouquet.tv  (IPTV Stream)

`#SERVICE 4097:0:1:1:0:0:0:0:0:0:https%3a//edge-uk2.manoto.click/live.m3u8

#DESCRIPTION Manoto TV
`
please see there are missing ":Manoto TV" behind m3u8 at end 
once adding and stream playing OK

**Comment by DYefremov** [comment]
> problem are in bouquet.tv (IPTV Stream)
> 
> `#SERVICE 4097:0:1:1:0:0:0:0:0:0:https%3a//edge-uk2.manoto.click/live.m3u8
> 
> #DESCRIPTION Manoto TV

And how did this stream end up in this file?

**Comment by luxorko** [comment]
regarding downloading bouquet from stb to demon:

-open demon (do not click else just on icon for downoading)
-click straight on downloand icon
![image](https://user-images.githubusercontent.com/65136999/223702068-128e58f7-8f10-481f-b1b3-f9077f122eaf.png)

and error showing

if 
-open demon
- click anywhere like on "File or bouquet list...."
- then downloading icon = error not showing 

could you repeat please

**Comment by luxorko** [comment]
> And how did this stream end up in this file?

enigma2 stb streaming correctly, if adding channels name behind m3u8 also no problem

**Comment by DYefremov** [comment]
> enigma2 stb streaming correctly, if adding channels name behind m3u8 also no problem

This file is not for that. If you add something manually, you must know exactly what you are doing.

> could you repeat please

I don't see any problems.

**Comment by DYefremov** [comment]
> > enigma2 stb streaming correctly, if adding channels name behind m3u8 also no problem
> 
> This file is not for that. If you add something manually, you must know exactly what you are doing.
> 
> > could you repeat please
> 
> I don't see any problems.

P.S. If such problems occur, without the full set of settings, such requests will be closed and ignored!

**Comment by luxorko** [comment]
> 




> P.S. If such problems occur, without the full set of settings, such requests will be closed and ignored!

this what i done now; also checked last 5 version of Demon and same behaviors

**Comment by luxorko** [comment]
> This file is not for that. If you add something manually, you must know exactly what you are doing.

now know what causes a problem. (Incrorrect created bouquet) .bouquet got from net. somewhere

should be closed now.

**Comment by DYefremov** [comment]
Ok. 

> enigma2 stb streaming correctly, if adding channels name behind m3u8 also no problem

What works for you doesn't mean it will work for everyone! Enigma2 is a big zoo. And I have neither the time nor the desire to guess what and how you manually enter into your files.  Sorry. But...

Closed!

**Comment by luxorko** [comment]
its realy strange 
this ara url stream

`https://edge-uk2.manoto.click/live.m3u8`

if thease url add to Demon like new IPTV channel  - its working
and bouquet looks like 
`#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3A//edge-uk2.manoto.click/live.m3u8:manot

#DESCRIPTION manot`

if i add bouquet.tv  without  "m3u8:manot" to demon - stream not working in Demon but working in enigma2 receiver 

`#SERVICE 4097:0:1:0:0:0:0:0:0:0:https%3A//edge-uk2.manoto.click/live.m3u8

#DESCRIPTION manot`
 
any idea ??

**Comment by DYefremov** [comment]
> any idea ??

I think if you use an editor, then you need to use an editor. If you want to enter data manually, then I see no point in using the editor.  DemonEditor uses a **valid type of IPTV description** (format) - and this is the main thing. And it also uses this format to get information about the link. Enigma2 (all or some distributions) may take a different approach, ignoring or omitting any data (eg stream description).
