### ISSUE TITLE
Open ATV7.0 ; 7.1

### ISSUE THREAD

**Issue by luxorko** [DYefremov/DemonEditor#67]
quick report - after sending files to image atv 7.0 and 7.1, user.bouqet not vissible on TV screen, but they are in the folder etc/enigma2/ . thank you

**Comment by DYefremov** [comment]
Hi,
I'm not sure that problem is in the program, because:
1. This branch is not stable. And can present more surprises. Just wait for updates.
2. I also have 7.0 build from 19.02.2022 for testing. I don't see any problems with this. 

If you are sure that the problem is in the program or Enigma2 settings, then send me your settings set. I'll test it on my Box.
